name: Bug report
description: Report a reproducible bug in OVC
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include clear reproduction steps.

  - type: input
    id: version
    attributes:
      label: Version
      description: Release tag or commit SHA
      placeholder: v0.3.3
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected component
      options:
        - hytale-plugin
        - voice-app
        - docs
        - ci/release
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Exact steps to reproduce the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots / stack traces
      render: shell
    validations:
      required: false
